#!/usr/bin/env python3
"""Generate the repo indexes from study-plan.yaml.

    python3 scripts/build_index.py             # update README.md and curricula/*.md
    python3 scripts/build_index.py --scaffold  # also create missing course folders

Requires PyYAML: pip install -r scripts/requirements.txt
"""
import argparse
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
PLAN = ROOT / "study-plan.yaml"
TEMPLATES = ROOT / "templates"
START, END = "<!-- INDEX:START -->", "<!-- INDEX:END -->"
GENERATED = "<!-- Generated by scripts/build_index.py from study-plan.yaml: do not edit by hand. -->"

STATUSES = {"todo": "⬜ To do", "draft": "🟡 Draft", "done": "✅ Done"}
COMMON = "🟢 Common"
ELECTIVE = "🎯 Elective"
FREE_CHOICE_ECTS = 12


def fail(msg):
    sys.exit("study-plan.yaml: " + msg)


def load_plan():
    plan = yaml.safe_load(PLAN.read_text(encoding="utf-8"))
    curricula = plan["curricula"]
    seen = set()
    for c in plan["courses"]:
        for field in ("slug", "name", "ects", "year"):
            if field not in c:
                fail("course without '{}': {}".format(field, c))
        if c["slug"] in seen:
            fail("duplicate slug: " + c["slug"])
        seen.add(c["slug"])
        c.setdefault("semester", None)
        c.setdefault("curricula", [])
        c.setdefault("modules", [])
        c.setdefault("status", "todo")
        c["contributors"] = c.get("contributors") or []
        if c["status"] not in STATUSES:
            fail("{}: invalid status '{}' (allowed: {})".format(c["slug"], c["status"], ", ".join(STATUSES)))
        for key in c["curricula"]:
            if key not in curricula:
                fail("{}: undefined curriculum '{}'".format(c["slug"], key))
    return plan


# Rendering

def course_link(c, prefix):
    name = "**[{}]({}courses/{}/)**".format(c["name"], prefix, c["slug"])
    if c["modules"]:
        name += "<br><sub>{}</sub>".format(" · ".join(m["name"] for m in c["modules"]))
    return name


def contributors(c):
    people = []
    for p in c["contributors"]:
        p = str(p).strip()
        people.append("[{0}](https://github.com/{1})".format(p, p[1:]) if p.startswith("@") else p)
    return ", ".join(people)


def status(c):
    return STATUSES[c["status"]]


def curriculum_badge(c, plan):
    keys = c["curricula"]
    if not keys:
        return ELECTIVE
    if len(keys) == len(plan["curricula"]):
        return COMMON
    return " ".join(plan["curricula"][k]["badge"] for k in keys)


def table(header, rows):
    lines = ["| " + " | ".join(header) + " |", "|" + "|".join("---" for _ in header) + "|"]
    lines += ["| " + " | ".join(str(x) for x in r) + " |" for r in rows]
    return "\n".join(lines)


def progress(courses):
    counts = {k: sum(c["status"] == k for c in courses) for k in STATUSES}
    return "**Progress:** ✅ {done} done · 🟡 {draft} draft · ⬜ {todo} to do, out of {n} courses.".format(
        n=len(courses), **counts)


def main_index(plan):
    courses = plan["courses"]
    core = [c for c in courses if c["curricula"]]
    electives = [c for c in courses if not c["curricula"]]
    links = " · ".join("[{}](curricula/{}.md)".format(v["name"], v["slug"]) for v in plan["curricula"].values())
    header = ("Course", "ECTS", "Curriculum", "Status", "Contributors")

    out = [progress(courses), "", "**Curricula:** " + links, ""]
    for year in sorted({c["year"] for c in core}):
        out += ["### Year {}".format(year), ""]
        in_year = [c for c in core if c["year"] == year]
        for sem in (1, 2):
            group = [c for c in in_year if c["semester"] == sem]
            if not group:
                continue
            rows = [(course_link(c, ""), c["ects"], curriculum_badge(c, plan), status(c), contributors(c))
                    for c in group]
            out += ["#### Semester {}".format(sem), "", table(header, rows), ""]

    out += ["### Free-choice courses", ""]
    if electives:
        rows = [(course_link(c, ""), c["ects"], ELECTIVE, status(c), contributors(c)) for c in electives]
        out += [table(header, rows), ""]
    else:
        out += ["_None yet. Add the ones you attend to `study-plan.yaml` with `curricula: []`._", ""]
    return "\n".join(out)


def curriculum_page(key, plan):
    cur = plan["curricula"][key]
    courses = sorted((c for c in plan["courses"] if key in c["curricula"]),
                     key=lambda c: (c["year"], c["semester"] or 0))
    rows = [(c["year"], c["semester"] or "", course_link(c, "../"), c["ects"], status(c), contributors(c))
            for c in courses]
    return "\n".join([
        GENERATED,
        "",
        "# {} curriculum".format(cur["name"]),
        "",
        "Courses of the **{}** curriculum: {} ECTS, plus {} ECTS of free-choice courses. "
        "Back to the [main index](../README.md).".format(
            cur["name"], sum(c["ects"] for c in courses), FREE_CHOICE_ECTS),
        "",
        progress(courses),
        "",
        table(("Year", "Sem.", "Course", "ECTS", "Status", "Contributors"), rows),
        "",
    ])


def replace_block(path, content):
    text = path.read_text(encoding="utf-8")
    if START not in text or END not in text:
        sys.exit("{}: markers {} / {} not found".format(path.name, START, END))
    head, rest = text.split(START, 1)
    _, tail = rest.split(END, 1)
    path.write_text("{}{}\n{}\n{}{}".format(head, START, content, END, tail), encoding="utf-8")


# Scaffolding

def render_template(template, **values):
    text = (TEMPLATES / template).read_text(encoding="utf-8")
    for k, v in values.items():
        text = text.replace("{{" + k + "}}", str(v))
    return text


def write_if_missing(path, content):
    if not path.exists():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def keep(directory):
    directory.mkdir(parents=True, exist_ok=True)
    if not any(directory.iterdir()):
        (directory / ".gitkeep").touch()


def scaffold(plan):
    for c in plan["courses"]:
        base = ROOT / "courses" / c["slug"]
        if c["modules"]:
            rows = ["| {} | {} | [summary]({s}/summary.md) · [notes]({s}/notes/) |".format(
                m["name"], m.get("ects", "n/a"), s=m["slug"]) for m in c["modules"]]
            contents = "\n".join(
                ["## Modules", "", "| Module | ECTS | |", "|---|---|---|"] + rows +
                ["", "- [Exercises and past exams](exercises/)"])
            units = [(base / m["slug"], m["name"], "../../../") for m in c["modules"]]
        else:
            contents = "\n".join([
                "## Contents", "",
                "- [Summary](summary.md)",
                "- [Lecture notes](notes/)",
                "- [Exercises and past exams](exercises/)",
            ])
            units = [(base, c["name"], "../../")]

        sem = c["semester"]
        period = "Year {}, semester {}".format(c["year"], sem) if sem else "Year {}".format(c["year"])
        curricula = ", ".join(plan["curricula"][k]["name"] for k in c["curricula"]) or "Free choice"
        write_if_missing(base / "README.md", render_template(
            "course-README.md", name=c["name"], code=c.get("code", "n/a"), ects=c["ects"],
            period=period, curricula=curricula, contents=contents))
        for directory, name, root in units:
            write_if_missing(directory / "summary.md", render_template("summary.md", name=name, root=root))
            keep(directory / "notes")
        keep(base / "exercises")
        keep(base / "assets")


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--scaffold", action="store_true", help="create missing course folders")
    args = parser.parse_args()

    plan = load_plan()
    if args.scaffold:
        scaffold(plan)
    replace_block(ROOT / "README.md", main_index(plan))
    for key, cur in plan["curricula"].items():
        path = ROOT / "curricula" / "{}.md".format(cur["slug"])
        path.parent.mkdir(exist_ok=True)
        path.write_text(curriculum_page(key, plan), encoding="utf-8")


if __name__ == "__main__":
    main()
